- src/bkz.cpp
the preprocessing used the "parent" flags and auto abort parameters instead of the ones specified in the preprocessing parameters.
> fix parameters in bkz's local preprocessing

- Makefile.am
- configure.ac
- src/Makefile.am
Switching to README.md created some minor problems:
- We don't obey the GNU project's recommendations any more by dropping the README file
- tarball creation would fail because it still tried to include README.html
> Readme fixes 

- .travis.yml
Travis doesn't let us specify arbitrary e-mail addresses for e-mail notification. Thinking about it, this is a good thing as it prevents us from getting all kinds of notifications for forks. Hence, let's remove that section of the config file.
> Travis won't send e-mail to arbitrary e-mail addresses

- src/bkz.cpp
- src/bkz.h
- src/defs.h
- src/dpe.h
- src/main.cpp
- src/main.h
- src/nr.cpp
- src/svpcvp.cpp
- src/svpcvp.h
Rebasing screwed up my commit chain so I have recreated this pull request. 
It adds the possibility of using the Gaussian Heuristic enumeration bound in BKZ with the BKZ_GH_BND flag and the ghFactor parameter or the -bkzghbound command with a ghFactor. BKZ will then use ghFactor*GH^2 as its enumeration bound instead of the usual (length of the current shortest vector), but only if the block size of the enumeration is bigger than 30. If a vector is not found during the enumeration, the current vector is kept and it continues with the next index. Note that this is a heuristic, and BKZ-reducedness will no longer be guaranteed. In order to compute the GH value it uses the exponential function which was not properly implemented for dpe, so I added a hack fix to dpe.h (and nr.cpp/nr.h), similar …
> BKZ with GH bound + SVPPruning with user bound

- src/nr.cpp
- src/nr.h
Currently, random number generation works for Z_NR class only when the data type is mpz_t.
Have added methods to generate random numbers for types long and double using random number functions of GMP.
> Generating random numbers for Z_NR

- tests/test_lll.cpp
Optional precision for isLLLReduced (required by quaddouble-wrapper branch)
> Test precision

- src/fplll.cpp
All the long double templates are disabled for cygwin, but one template instantiation
in fplll.cpp wasn't guarded. Previously failed with:
.libs/fplll.o:fplll.cpp(.text$_ZN5fplll6MatGSOINS_4Z_NRIA1_12__mpz_structEENS_5FP_NRIeEEE12updateGSORowEii[_ZN5fplll6MatGSOINS_4Z_NRIA1_12__mpz_structEENS_5FP_NRIeEEE12updateGSORowEii]+0xba): undefined reference to `fplll::FP_NR<long double>::is_nan() const'
and multiple other missing definitions for FP_NR<long double>.
I added an #ifdef guard to disable that one too.
I haven't tried the fix on any other platforms, only cygwin.
> Minor tweak to get it building on cygwin.

- src/bkz.cpp
- src/defs.h
- src/enumerate.cpp
- src/enumerate.h
- src/svpcvp.cpp
This adds the ability to enumerate shortest vectors in the dual instead of the primal to the Enumeration class. For details on the dual enumeration algorithm, see http://eprint.iacr.org/2015/1123. 
Access to the new enumeration is provided through the shortestVector function (in svpcvp.cpp) and a new flag: SVP_DUAL.
> dual enumeration

- src/enumerate.cpp
After the dual enumeration completed, the maxDist norm was not updated correctly. So the function worked and returned a shortest dual vector, but the maxDist variable still contained the old value.
> bugfix in the dual enumeration

- src/Makefile.am
- src/bkz.cpp
- src/bkz.h
- src/fplll.cpp
- src/gso.cpp
- src/gso.h
- src/lll.cpp
- src/lll.h
The way we structure fplll means that not all member functions/methods are necessarily instantiated in the shared library, making it difficult to use fplll as a library for anything but the highlevel functions such as ```bkzReduction```. This pull requests inlines a few more helper function and installs a few more headers to make it easier to use lower-level functions from fplll as a third party. These fixes are required for [fpylll](https://github.com/malb/fpylll).
> Fixes for fplll as a library

- src/gso.h
This pull requests adds several utility functions to dump the internal state of the GSO to double arrays for further consumption by third party libraries.
> dump to double arrays

- src/gso.cpp
- src/gso.h
moved constructor of MatGSO to header
> fix for dual svp test and clang

- src/enum/enumerate.cpp
- src/enum/enumerate.h
- src/enum/evaluator.cpp
- src/enum/evaluator.h
- src/svpcvp.cpp
- src/svpcvp.h
- enumeration,evaluator:
-- added support auxiliary solutions
-- added support subsolutions
- svpcvp:
-- cleaned up a bit (removed radius for shortestVectorEx, unused functions)
-- added support for subsolutions in shortestVectorPruning (currently nowhere used)
> keeping auxiliary solutions & subsolutions in enumeration

- fplll/bkz.cpp
This fix is required for fpylll
> force instantiation of BKZAutoAbort templates

- fplll/bkz.cpp
bkz.cpp: In member function ‘const fplll::Pruning& fplll::BKZReduction<FT>::get_pruning(int, int, const fplll::BKZParam&) const [with FT = fplll::FP_NR<double>]’:
bkz.cpp:121:3: warning: ‘gh_max_dist.fplll::FP_NR<double>::data’ is used uninitialized in this function [-Wuninitialized]
if (f < max_dist)
^
bkz.cpp:179:6: note: ‘gh_max_dist.fplll::FP_NR<double>::data’ was declared here
FT gh_max_dist;
^
> fix compiler warning about unitialised values

- fplll/bkz.cpp
- fplll/enum/enumerate.cpp
- fplll/enum/evaluator.cpp
- fplll/enum/evaluator.h
- fplll/nr/nr_FP.inl
- fplll/nr/nr_FP_d.inl
- fplll/nr/nr_FP_dd.inl
- fplll/nr/nr_FP_dpe.inl
- fplll/nr/nr_FP_ld.inl
- fplll/nr/nr_FP_mpfr.inl
- fplll/nr/nr_FP_qd.inl
- fplll/svpcvp.cpp
- tests/Makefile.am
- tests/test_nr.cpp
- tests/test_svp.cpp
- deal with fallout because 'FP_NR<double> a = 0' now is ambigious
- add tests for new routines
- also extend test coverage of test_nr
fixes #126
> add string conversion for FP_NR

- fplll/pruner.cpp
- fplll/pruner.h
typically output params are provided before input params, cf. GMP/MPFR APIs.
> convention on parameter ordering

- fplll/enum/enumerate_base.h
Should fix https://github.com/fplll/fplll/issues/172
> enumerate_base.h: fix warning due to compilation for unnecessary kk=maxdim-1

- fplll/Makefile.am
- fplll/enum/enumerate_base.h
Relative paths in the include directives for enumeration_base.h needed
to be fixed. As the respective paths are already included by the
compiler, we do not need to point the preprocessor to the correct
subdirectory.
> this commit fixes issue #203, building in a subdirectory

- fplll/latticegen.cpp
Calling, e.g.,
./latticegen n 10 10 10
should return a fatal error, instead of falling through and returning a
zero matrix.
> Don't fail silently on invalid latticegen options

- .travis.yml
Add macOS and g++-6 in Travis matrix. FYI, the test with g++-6 does not catch #218.
> Travis/more tests: macOS and g++-6

- fplll/bkz.cpp
- fplll/enum/enumerate.cpp
- fplll/enum/enumerate_base.cpp
- fplll/enum/evaluator.cpp
- fplll/enum/evaluator.h
- fplll/latticegen.cpp
- fplll/nr/matrix.cpp
- fplll/nr/nr_FP.inl
- fplll/svpcvp.cpp
* Evaluator classes reshaped:
Evaluator<FT>
\- FastEvaluator<FT>: Evaluator<FT>
\- ErrorBoundedEvaluator: Evaluator<Float>
\- FastErrorBoundedEvaluator: ErrorBoundedEvaluator
\- ExactErrorBoundedEvaluator: ExactErrorBoundedEvaluator
* Previously FastEvaluator<Float> had extra behaviour compared to FastEvaluator<FT>
this has now been moved into ErrorBoundedEvaluator for greater clearity
* Instead of auxsolutions (i.e., a shortest vector and a vector of other short vectors)
Evaluator stores all its solutions in a multimap (ordered from longest to shortest),
and updates this multimap and the enumeration bound according to a given EvaluatorStrategy:
* EVALSTRATEGY_BEST_N_SOLUTIONS:
Keep up to N=<nr_solutions> sols, adjust enumeration bound only on the N-th shortest solution.
Since the …
> Evaluator recode

- fplll/enum/evaluator.cpp
- fplll/enum/evaluator.h
- fplll/svpcvp.cpp
- fplll/svpcvp.h
Two things would need to get better:
1) the lengths of the auxiliary solutions are not absolute but relative to the nomExpo and the like. We would need to write something like line 143 of enumerate.cpp to scale back to absolute. I am thinking of the best way to do it.
2) the "SVP" as returned by enumerate is no longer the smallest (when aux solutions are requested) because it is the last enumerated candidate below the bound. So it may not be what we wish...
> Handling multiple solutions below a bound

- fplll/Makefile.am
- fplll/enum/enumerate.h
- fplll/enum/enumerate_base.h
- fplll/enum/enumerate_ext.cpp
- fplll/enum/enumerate_ext.h
This paves the way for using external multithreaded / mpi / GPU enumeration libraries with fplll.
You can enable an external enumeration library with
`set_external_enumerator(&external_enumeration_function)`.
When the external enumerator is called and returns -1 to indicate it can't run the job,
it automatically falls back to fplll enumeration.
This wrapper code works as expected and 
has been tested in combination with:
https://github.com/cr-marcstevens/fplll-extenum
(Note: that extenum library gives sane and very similar results, but not exactly identical to fplll enumeration yet.)
> Added support for external enumeration libraries.

- fplll/bkz.cpp
- fplll/lll.cpp
- fplll/lll.h
Enables babai (i.e., LLL size-reduction) not  to use the first basis vectors.
Changes enumeration post_processing in BKZ
* if the solution vector contains a 1, use this to eliminate the linear dependency
* if not, proceed as before
> Stable lll in bkz

- fplll/bkz.cpp
- fplll/gso.cpp
- fplll/gso.h
repairing gaussian_heuristic to handle very large dimension (switching from tgamma to lgamma to avoid exponent overflow in double).
Rename the function to something more faithful to its behavior : adjust_radius_to_gh_bound .
> Gaussian Heuristic repaired and renamed

- configure.ac
- fplll/enum/enumerate_base.h
- fplll/fplll_config.h.in
Since this feature--admittedly I don't fully understand what it does--was added (#191) libfplll does not build on Cygwin.
This is in part for two reasons: it results in a huge number of binary sections (>40000) in the enumerate_base.o object file.  On Windows this is a known problem due to limitation in the COFF file format.  This can be gotten around somewhat with the `-mbig-obj` flag to the GNU assembler, and in the past that's worked for me to get around this problem.
In this case, however, while I can get the file to compile/assemble with `-mbig-obj`, linking libfplll fails.  I haven't run into this problem before (maybe just by luck?) but as far as I can tell it seems to be a bug *somewhere* in the (slightly old) bfd/binutils on Cygwin.  It seems to be using a signed short somewhere …
> Allow the recursive enumerate feature to be disabled at configure time

- tests/test_nr.cpp
- tests/test_pruner.cpp
Self-explanatory--don't compile tests that use `long double` where that isn't supported (see #212).
With this fixed, `make check` can pass on Cygwin.
> Don't test long double functionality without FPLLL_WITH_LONG_DOUBLE

- tests/test_pruner.cpp
Inequalities in test_pruner now tolerates small numerical errors.
The test still pass on my 64 bits machine. Not tested yet on a 32 bit env.
> Repairing test_pruner for #245

- fplll/sieve/sieve_gauss.cpp
- fplll/sieve/sieve_gauss.h
- fplll/sieve/sieve_gauss_2sieve.cpp
- fplll/sieve/sieve_gauss_3sieve.cpp
- fplll/sieve/sieve_gauss_4sieve.cpp
- fplll/sieve/sieve_main.cpp
- tests/test_sieve.cpp
Does anyone know how to fix the error "codecov/patch — No report found to compare against"?
> Sieve api 248

- fplll/bkz.cpp
- fplll/bkz.h
- fplll/nr/matrix.cpp
- fplll/nr/matrix.h
- tests/test_svp.cpp
bkz reduction runs with long integers instead of mpz, if the numbers in the basis are small enough. the bkz reduction is templated with an integer type, the switch happens in the bkz_reduction_f function, so the user interface (bkz_reduction(...)) did not change.
> BKZ with Z_NR<long>

- fplll/bkz.cpp
- fplll/bkz.h
SDB and SLD should only output stuff when asked to do so
> Fix output of sdb and sld in non verbose mode

- tests/test_bkz.cpp
- tests/test_cvp.cpp
- tests/test_gso.cpp
- tests/test_lll.cpp
- tests/test_lll_gram.cpp
- tests/test_sieve.cpp
- tests/test_svp.cpp
- tests/test_utils.h
This pull request is supposed to solve Issue #304. I would prefer not to check if A or b are empty, and check instead if the files are correctly opened, but I hope it will be acceptable. On the contrary to the message that reports the issue, only `test_bkz` fails silently.
> Make distcheck for test_bkz

- tests/test_bkz.cpp
- tests/test_cvp.cpp
- tests/test_gso.cpp
- tests/test_lll.cpp
- tests/test_lll_gram.cpp
- tests/test_sieve.cpp
- tests/test_svp.cpp
In Issue #309, @malb asked about the use of the indirect include of test_utils.h.
Since test_utils.h was added to ```EXTRA_DIST``` in `tests/Makefile.am` in commit `b4f55a25ca0041b4ed70a2bc2aa4c2b23df1cdfc`, this strange indirect include is no more necessary.
> Remove relative path to test_utils.h.

- CONTRIBUTING.md
- fplll/main.cpp
I fix spelling errors reported in Issue #319. I also remove a colon in the documentation section of CONTRIBUTING.md.
> Trivial typos

- fplll/nr/nr_FP_dd.inl
- fplll/nr/nr_FP_misc.inl
In nr_FP_misc.inl, set_f, the conversion from mpz_t to dd_real was using mpz_get_d, 
modified through high and low doubles. 
In nr_FP_dd.inl, set_mpfr, the conversion from mpfr to dd_real was using mpfr_get_ld, 
modified through high and low doubles.
> dd wrapper

- fplll/gso.cpp
- fplll/gso.h
- fplll/nr/matrix.h
- fplll/nr/numvect.h
- fplll/sieve/sieve_gauss.cpp
- fplll/svpcvp.cpp
- fplll/util.h
I propose to remove the function `scalar_product` from ` fplll/util.h` since it is the same as the one described in `fplll/nr/matrix.h`. I also propose to only use the definition of `dot_product` in `fplll/nr/numvect.h` and use it in `fplll/nr/matrix.h`. My tests seem to show that the running times of LLL are not increased by this last modification.
Question : is a function that computes the square norm of a vector (MatrixRow, NumVect) needed? I choose to not have such a function.
> Dot product

- .travis.yml
- fplll/lll.h
Currently, if size_reduction is called before lll is called, we end up with a SEGFAULT.
See https://github.com/fplll/fpylll/issues/110
The peformance penalty should be negligible since there are a few ifs in size_reduction. Also,
branch prediction will be able to do the right thing here, I think.
> extend babai vectors when calling size_reduction

- README.md
- configure.ac
- fplll.pc.in
- fplll/Makefile.am
- fplll/defs.h
- tests/Makefile.am
The goal of this PR is to allow to use mpir instead of gmp. The mechanism is maybe not optimal, since it is needed to use, during the `./configure` step, the option `--enable-mpir`. This is maybe a step to be able to compile `fplll` on Windows, as suggested in the wiki of the fplll days 4.
> Can use mpir instead of gmp

- README.md
- fplll/main.cpp
This PR removes the ability to use options:
* `-c` and `-r`, since these options were ignored
* `-m [fastearly|heuristicearly]` and prefer the use of `-m [fast|heuristic] -y`
> Unused option fplll tool

- configure.ac
- fplll/fplll_config.h.in
- fplll/nr/nr_FP_mpfr.inl
Since version 4.0.0 of mpfr,
> `mpfr_root` [is] deprecated and will be removed in a future release
These changes must allow to use `mpfr_rootn_ui` instead of `mpfr_root` if mpfr 4.0.0 is installed without breaking the ability to use older versions of mpfr.
> Deprecated function in mpfr 4.0.0.

- fplll/nr/dpe.h
- fplll/sieve/sieve_gauss_2sieve.cpp
- fplll/sieve/sieve_gauss_3sieve.cpp
- fplll/sieve/sieve_gauss_4sieve.cpp
This fixes two issues when compiling on Solaris with GCC-5.4.0.
The first is an issue with `pow()`:
```
nr/dpe.h: In function 'void dpe_pow_si(dpe_struct*, const dpe_struct*, unsigned int)':
nr/dpe.h:718:35: error: call of overloaded 'pow(const double&, const unsigned int&)' is ambiguous
DPE_MANT(x) = pow(DPE_MANT(y), k);
```
The second is GCC bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=10200
The existence of a templated `norm` function causes GCC to misparse `if (p->norm < v->norm)`
> Fix Solaris issues

- fplll/gso_gram.cpp
- tests/test_lll_gram.cpp
Resolved the Gram-matrix bug by replacing `n_known_rows` in the Gram-operations by the full dimension `d`. 
This makes sense, because only a partial operation [up tp `n_known_rows`] on the Gram-matrix is not consistent and causes irregularities. In larger dimensions, this cause distortion of the positive-definiteness, causing severe errors during LLL-reduction.
This particular code also occurs in gso.cpp. We could also replace `n_known_rows` by `d` there. Is there a reason that it is `n_known_rows`? **Edit: yes. If `enable_int_gram` the exact Gram matrix is stored, but only up to `n_known_rows`, therefore that this code should stay in gso.cpp.**
> Possibly resolved the Gram bug

- fplll/bkz.cpp
- fplll/bkz.h
- fplll/enum/evaluator.cpp
- fplll/gso_gram.cpp
- fplll/gso_gram.h
- fplll/main.cpp
- fplll/nr/nr_FP_misc.inl
- fplll/sieve/sieve_main.cpp
- fplll/wrapper.cpp
- tests/test_bkz.cpp
- tests/test_gso.cpp
- tests/test_nr.cpp
- tests/test_pruner.cpp
- tests/test_svp.cpp
This PR tries to remove warnings reported by adding `-Wextra -DDEBUG` to the `CXXFLAGS` variable of the configuration of `fplll`.
> Suppress warnings reported by Wextra

- .travis.yml
- Doxyfile
- configure.ac
Hi all,
Fplll 5.2.1 was released on 18 May 2018 and is available at
https://github.com/fplll/fplll/releases/tag/5.2.1
This release is a bugfix release. Major changes in fplll-5.2.1 compared to fplll-5.2.0:
- [Possibly resolved the Gram bug](https://github.com/fplll/fplll/pull/349) by Koen de Boer
- [Fix Solaris issues](https://github.com/fplll/fplll/pull/348) by Jeroen Demeyer
- [Unify randomness on 32-bit and 64-bit systems](https://github.com/fplll/fplll/pull/345) by Martin Albrecht
- [Adding Windows 10 instructions to the readme](https://github.com/fplll/fplll/pull/337) by Thijs Laarhoven
- [Can use mpir instead of gmp](https://github.com/fplll/fplll/pull/335) by Laurent Grémy
- [Dot product](https://github.com/fplll/fplll/pull/326) by Laurent Grémy
- [make MatGSOGram.row_swap …
> Release 5.2.1

- tests/test_bkz.cpp
- tests/test_cvp.cpp
- tests/test_gso.cpp
- tests/test_lll.cpp
- tests/test_lll_gram.cpp
- tests/test_sieve.cpp
- tests/test_svp.cpp
- tests/test_utils.h
This commit removes the warnings produced by `-Wcatch-value`, probably enabled by default in gcc-8. This is also the occasion to use a unified version to check if the files are correctly read.
> Remove Wcatch-value and unify way to check if files are read.

- fplll/bkz.h
- fplll/enum/enumerate.cpp
- fplll/enum/enumerate_base.cpp
- fplll/enum/enumerate_base.h
- fplll/enum/enumerate_ext.cpp
- fplll/enum/enumerate_ext.h
- fplll/enum/evaluator.cpp
- fplll/enum/evaluator.h
- fplll/gso.h
- fplll/gso_gram.h
- fplll/gso_interface.h
- fplll/hlll.cpp
- fplll/hlll.h
- fplll/householder.cpp
- fplll/lll.cpp
- fplll/main.cpp
- fplll/nr/matrix.cpp
- fplll/nr/matrix.h
- fplll/pruner/pruner.cpp
- fplll/pruner/pruner_optimize_tc.cpp
- fplll/sieve/sampler_basic.cpp
- fplll/sieve/sieve_gauss_2sieve.cpp
- fplll/sieve/sieve_gauss_str.h
- fplll/svpcvp.cpp
- fplll/util.cpp
- fplll/wrapper.cpp
- tests/test_gso.cpp
Related to issue https://github.com/fplll/fplll/issues/362
Other file have been modified since I did make check-style I think. 
The size of the exponent was tested in proved_loop but not in last_lll, the exponent size of 
dd_real is the same the one of double. See the exponent test put now at line 267 of wrapper.cpp
(Besides, a remark : in proved_loop, line 214 could be reached (WITH_QD), with precision 
between numeric_limits<double>::digits  and  PREC_DD, could potentially leadi to a failure since use 
of dpe_t. However, in Wrapper::lll(), the call is heuristic_loop(increase_prec(prec_d)) and 
the increased precision seems to be greater there than PREC_DD.)
> Fixing issue #362

- README.md
When trying to install fplll again in Windows 10, I had the minor issue mentioned above, and found a simple fix online -- it might be useful for others too if they encounter the same issue.
> Added solution for potential Win10 issue

- README.md
lxrun /install is now deprecated - in newer versions of Windows 10 one has to install a Linux distribution from the Windows store. 
The instructions now reflect these changes. There's also a note about dependencies not being required until the WSL is active.
> Changed Readme.md for recent WSL changes

- README.md
- fplll/nr/numvect.h
When running the "make latsieve command" I get a "no rule" error - it appears that this isn't a valid target anymore, and that we always build the sieve directory & related classes under the regular make command.
As a result, I've removed the "make latsieve" sentence.
This might be irrelevant though if issue #369 is finalised before the next release.
> Optional latsieve isn't a thing anymore.

- fplll/pruner/pruner.h
I have been testing builds for fplll 5.3.0 and fpylll 0.5.0dev for Fedora.  The default Fedora build flags include -D_GLIBCXX_ASSERTIONS.  This led to test failures in fpylll due to out of bounds vector accesses in the fplll code.  This commit fixes the two such out of bounds accesses found by the fpylll tests.  (I highly recommend that you build with -D_GLIBCXX_ASSERTIONS before running your tests, by the way.)
In the first hunk, note that min_pruning_coefficients always has length *d*, not n.  The fpylll test suite, at least, invokes this code in such a way that i / c can be equal to d and therefore one past the end of the min_pruning_coefficients vector.
In the second hunk, j can be as large as as dn (b.size()), and therefore on the first iteration of the loop, when i is j - 1, then …
> Fix out-of-bounds vector accesses in Pruner::enforce.

- fplll/hlll.cpp
- fplll/wrapper.cpp
Solve Issue #402 and let information "This is probably the first time this test is used" not be part of the build of the HLLL implementation.
> Cosmetic changes for HLLL

- configure.ac
- fplll.pc.in
- fplll/Makefile.am
- tests/Makefile.am
When no pkg-config file is present and when qd was automatically detected, the `-lqd` flag was winding up in `LIBS` rather than `LIBQD_LIBS`. The other linker flags that arise from the `AC_CHECK_LIB` macro also wind up in `LIBS`, so it makes sense to put `LIBS` in the pkg-config file, replacing some of the existing "custom" entries. The remaining commits attempt to eliminate the duplicate flags. Hopefully the individual commit messages explain.
> Fix the libraries listed in the pkg-config file

- README.md
Since it's now mandatory with Libqd (#407 ) we should at least mention it in the install docs. 
This addresses #410 indirectly.
> Added mention of pkg_config

- fplll/nr/nr_Z.inl
- fplll/nr/nr_Z_d.inl
- fplll/nr/nr_Z_l.inl
- fplll/nr/nr_Z_mpz.inl
#417 asks for copy-assignment/move-assignment constructors for the integer types.
Thankfully, C++ compilers mostly implement this for us; the only important bit is adding in the copy constructors (I didn't add in move-assignment because I don't think it's used anywhere else in fplll...).
This PR implements #417 . It's now possible to write:
``` 
mpz_t temp;
mpz_init(temp, 5);
Z_NR<mpz_t> out(temp)
```
and:
``` Z_NR<mpz_t> out = Z_NR<mpz_t>(temp); ```
as requested. 
It also does it for all of the integral types - so mpz_t above could be replaced by ```long``` or ```double``` and it would still work.
Note; I didn't implement the request for a % operator.
> Added constructors from  #417

- fplll/nr/nr_Z.inl
- fplll/nr/nr_Z_d.inl
- fplll/nr/nr_Z_l.inl
- fplll/nr/nr_Z_mpz.inl
This is the second part from #417 - Z_NR now has a modulus operation. 
The implementation merely adds wrappers for Z_NR; internally, each method delegates to the modulus operations for the underlying types.
Usage is very similar to all of the other operations (add, mul etc). 
For example: 
```
Z_NR<mpz_t> out = 0;
Z_NR<mpz_t> radix = 5;
Z_NR<mpz_t> modulus = 3;
out.mod(radix, modulus);
```
Note that the template type parameters must be the same; I think mixing the types is a bad idea.
> Added modulus operation 

- fplll/main.cpp
The -bkzmaxtime was not parsed to function bkz() in main.cpp. Just added this.
> fix -bkzmaxtime in main.cpp

- fplll/bkz.cpp
- fplll/hlll.cpp
- fplll/lll.cpp
This pull request addresses #435 .
* Add ```verbose``` guard to calls to ```cputime``` in ```hlll.cpp```, ```lll.cpp``` and ```bkz.cpp```. Some of the calls mentioned in #435 are already wrapped inside an ```if``` statement that checks ```verbose```, so it doesn't make sense to double wrap these.
There's no new flag. In particular, in ```bkz.cpp``` every call relies exclusively on ```BKZ_DUMP_GSO```.
The reason why is because every  ```cputime```  call (other than the one changed in this PR) is already inside a check on ```BKZ_DUMP_GSO```; I don't think it makes sense to remove the call to ```cputime``` there, because it's probably a sensible default for ```BKZ_DUMP_GSO```. This is compounded by the fact that the call to ```print_tour``` is inside a check on ```BKZ_DUMP_GSO```; so this …
> Add verbose guard to cputime in hlll, lll and bkz

- fplll/enum-parallel/enumlib.cpp
- fplll/enum-parallel/enumlib.h
- fplll/enum-parallel/enumlib_dim.cpp
- fplll/enum/enumerate.cpp
- fplll/enum/enumerate.h
- fplll/enum/enumerate_base.cpp
- fplll/enum/enumerate_base.h
- fplll/enum/enumerate_ext.cpp
- fplll/enum/enumerate_ext.h
- tests/Makefile.am
- tests/test_counter.cpp
Following #440, this PR changes the counters in fplll from a single, ```uint64_t``` to an array, which contains a counter for each level. 
In particular:
* ```get_nodes()``` has become ```get_nodes(const int level=-1)```. If ```level=-1``` then the sum of all counters is returned.
* ```get_nodes_array()``` now exists. This primarily exists to return the counters from the external enumerator.
> Count nodes by level, rather than by tree

- README.md
We can install fplll in multiple ways. Shouldn't the readme talk about this?
This PR attempts to close a long-standing issue (#190) that pertains to describing some different ways to install fplll from pre-built packages. In particular, this PR describes how to install fplll from packages on the following platforms:
- Ubuntu and Debian
- MacOS
- Conda
- Docker.
It also makes some small wording changes to the WSL section (just small tweaks to my own wording from fplll days 5). This should make the readme clearer.
I've checked all of the instructions but the Docker ones (this simply refers the user to the repository with the Docker images); these all work . 
It's possible though that I've screwed something up, and I'd appreciate it if someone could check at least some subset of these …
> Installation from package instructions (fixes #190) 

- configure.ac
- fplll/Makefile.am
- fplll/enum-parallel/enumlib.cpp
- fplll/enum-parallel/enumlib.h
- fplll/enum-parallel/enumlib_dim.cpp
- fplll/enum/enumerate.h
- fplll/enum/enumerate_base.h
- fplll/enum/enumerate_ext.cpp
- fplll/enum/enumerate_ext.h
- fplll/enum/enumerate_ext_api.h
- fplll/fplll_config.h.in
This PR makes it possible to directly integrate any external enumeration into fplll and be used by default by fplll.
> Set a default external enumeration library

- fplll/gso_interface.h
At the moment I can't write this code:
``` 
template<typename Z, typename F>
void do_something(const MatGSO<Z_NR<Z>, FP_NR<F>>& gso) {
const auto r = gso.get_r_matrix();
}
```
Because ```get_r_matrix``` isn't a const function, even though it returns a const reference:
```
const Matrix<FT> &get_r_matrix() { return r; }
```
This PR fixes this by denoting this method (and I believe all others) in ```gso_interface.h``` that return const references as ```const```. Thus, the above method now reads as:
```
const Matrix<FT> &get_r_matrix() const { return r; }
``` 
Which enables the code snippet to compile.
> Make some methods in MatGSO const

- fplll/gso_interface.h
- fplll/nr/nr_FP.inl
- fplll/nr/nr_Z.inl
- fplll/wrapper.h
C++20 appears to have outlawed something that fplll had before: redundant typenames in destructors. In particular, the following isn't legal anymore:
```
template<typename F>
class F_Wrapper {
~F_Wrapper<F>();
};
```
The standard justifies this as fixing the defects identified in [CWG2237](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#2237)
Just remove the template parameters; they weren't ever necessary.
> Fix #474 -- remove redundant template parameters

- fplll/Makefile.am
This PR just removes the "using namespace fplll" line from  ```fplll/Makefile.am ``` due to the ticket #477.
Compulation, installation and make check all work locally. I also tested this by pre-processing the following test file:
```
#include<iostream>
#include<fplll.h>
int main() {
ZZ_mat<mpz_t> mat;
std::cin >> mat;
std::cout << mat ;
return 0;
}
```
Running ```gcc -E``` on this gives the following (explicitly shortened):
```
} 
```
In other words, the ```using namespace fplll``` is no longer present.
> Remove 'using namespace fplll' (fix #447)

- fplll/lll.h
- fplll/nr/nr_Z.inl
- fplll/util.cpp
This PR fixes #479 by replacing the statically instance of ```mpfr_t``` with a temporary on each call to the functions in ```LDConvHelper```. This is a definite performance regression, but I have no idea if these functions are used much.
> Fix for #479 - replace static mpfr with temporaries

- fplll/main.cpp
The CVP call from the commandline was missing the CVP-method parameter in the call.
Also, the flags were treated the same for SVP as for CVP, I splitted that into two.
> Use CVPM_PROVED for CVP

- fplll/bkz_param.cpp
This just adds the ```full_strategy_path``` to ```load_strategies_json```. This doesn't make any changes to the file path if it isn't fully qualified, so the original behaviour should be preserved. This should address #485 and https://github.com/fplll/fpylll/issues/221.
> Add full strategy path (c.f #485)

- configure.ac
There's a double-equals test here that doesn't work properly when `/bin/sh` is not bash. We simply change it to single-equals.
> configure.ac: fix bashism in --with-qd test.

- fplll/gso.h
- fplll/gso_gram.h
- fplll/gso_interface.h
At the moment we can't write:
```
template<typename ZT, typename FT>
void do_thing(const MatGSOInterface<ZT, FT>& gso) {
const auto rows = gso.get_rows_of_b();
...
}
```
Because the getters aren't marked as ```const```.  They should be -- both conceptually (we wouldn't expect this to change the underlying object), and in practice, since ```Matrix``` marks these functions as ```const```:
https://github.com/fplll/fplll/blob/9f780667b318edf28b53a778ecd9f06b2c0b8fcf/fplll/nr/matrix.h#L153-L154
This PR just makes those getters (e.g ```get_rows_of_b``` and ```get_cols_of_b```) ```const```.
> Make getters for rows and cols constant for the GSO.

- fplll/nr/nr_FP.inl
- fplll/nr/nr_FP_d.inl
- fplll/nr/nr_FP_dd.inl
- fplll/nr/nr_FP_dpe.inl
- fplll/nr/nr_FP_ld.inl
- fplll/nr/nr_FP_mpfr.inl
- fplll/nr/nr_FP_qd.inl
- tests/Makefile.am
- tests/test_ceil.cpp
At the moment fplll supports flooring and rounding ```FP_NR<F>```, but not ceiling. This PR just adds support for ceiling ```FP_NR<F>```.
> Add support for ceiling floating point numbers.

- tests/test_babai.cpp
TL;DR: ```long double``` isn't always 80 bits in length.
The old tests implicitly assumed that ```long double``` was more precise than ```double```:
https://github.com/fplll/fplll/blob/322b0a1c7db191a134ab3f7ab8af4597471b0af8/tests/test_babai.cpp#L86-L88
[However, this isn't true on all platforms](https://en.wikipedia.org/wiki/Long_double). Indeed, on my M1 Mac, both ```long double``` and ```double``` are 64-bits. 
This PR makes the behaviour of the test conditional on this detail. I also added some more printing, because it's easier to tell why the test is failing with more info :) 
This should address #500. Maybe we should add other platforms to the CI too?
> Fix failing babai test.

- tests/test_babai.cpp
Turns out I missed the case for ```long double``` being synonymous with ```__float128``` and a handful of other cases. This PR should finish #500.
> Make Babai test more robust for PPC etc.

- fplll/gso.h
It seems like the default dimension parameter was meant to be -1, not 1.
> Fix default dimension for Babai.

- fplll/fplll_config.h.in
Nothing was ever substituted for the template `@FPLLL_SONUM@`, so the template was appearing verbatim in the generated `fplll/fplll_config.h`. Since that isn’t a usable value, we know that nobody was relying on this particular macro as part of the API.
Fixes #509.
> Remove FPLLL_SONUM from fplll/fplll_config.h.in

- fplll/gso_interface.cpp
- fplll/gso_interface.h
- tests/test_gso.cpp
This provides a (hopefully) small speed up to calculation of the current slope, although this is probably negligible in the bigger picture.
- Remove any memory usage in the vector x as we can compute the numerator directly.
- The denominator is now calculated with: $$\sum^{n-1}_{i=0} \left(i - \frac{n-1}{2} \right)^2 = \frac{(n+1)n(n-1)}{12}.$$
- Change the documentation to say that the curve is a line fitted with least squares method.
> Compute denominator directly in slope calculation

- fplll/defs.h
`aarch64-darwin` does not have support for long doubles; please see the corresponding [issue](https://github.com/fplll/fpylll/issues/269) and [fix](https://github.com/fplll/fpylll/pull/270) in `fpylll` for more information.
> disable long doubles on aarch64-darwin

- .github/workflows/tests.yml
Turns out that Homebrew changed the install location for libraries when moving from x86_64 to Apple silicon. There's also a linker bug in the version of xcode that's used by GH by default, but that's resolvable by using the latest version of Xcode.
Fixes #522
> Fix CI on Macos 

- fplll/bkz.cpp
In bkz.cpp, the function bkz_reduction_f() only checks if the input basis b fits into the long with:
convert<long, mpz_t>(bl, b, 10)
The pull request also checks whether the input u and u_inv fit into the long. 
This hopefully fixes #525.
> fix convert mpz to long for u and u_inv in bkz.cpp. This hopefully fixes #525. 

- fplll/nr/nr_FP.inl
There was the following warning when running `make`, when compiling the C++ code with a modern compiler (i.e. one that supports C++20 but still compiles with C++11):
warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
note: remove the '< >'
More info, see: https://stackoverflow.com/questions/63513984/can-class-template-constructors-have-a-redundant-template-parameter-list-in-c2
> Remove warning for >=C++20 compilers

- .github/workflows/codecov.yml
fixes #539
See https://stackoverflow.com/questions/28004184/libtool-prefixes-objects-but-gcov-requires-them-without-prefix
> call gcov differently

- COPYING
- fplll/nr/dpe.h
The FSF is now remote-only and no longer has a physical address.
Updated `COPYING` from https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt, and updated the header of `fplll/nr/dpe.h` based on https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html#SEC4.
> Update LPGL 2.1 license text; update LGPL-2.1-or-later license notice
