- src/fplll.cpp
Just a test pull request to demo CI (don't merge)
> Test travis ci with broken branch

- src/fplll.cpp
> Revert "Test travis ci with broken branch"

- src/bkz.h
Documents some functions in the header-file for the bkz-algorithm (for computing the shortest vector).
> Adds documentation to bkz.h.

- README.md
- src/bkz.h
Fix bug in linear pruning and explain what level does in README.md
> Linear pruning

- src/bkz.h
> fix enableLinearPruning (again!)

- Makefile.am
- config.h.in
- configure.ac
- fplll.pc.in
Write [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/) to ease third party linking against fplll.
> write & install fplll.pc

- fplll/bkz.cpp
- fplll/bkz.h
- fplll/gso.cpp
- fplll/gso.h
I also discovered a bug while moving those around, also fixed in this PR.
> move dump_gso and friend

- fplll/pruner.cpp
- fplll/pruner.h
- tests/test_pruner.cpp
renorm is determined by the first shape only
> repaired renormalization bug

- fplll/bkz.cpp
- fplll/bkz.h
- fplll/bkz_param.cpp
- fplll/bkz_param.h
- fplll/main.cpp
based on https://github.com/fplll/fplll/pull/122#issuecomment-230489833 by @cr-marcstevens
> fix string handling

- fplll/enum/enumerate_base.h
> declare EnumerationBase destructor virtual

- fplll.pc.in
As reported by @gbonnoron  at fplll/fpylll/pull/30
> fix for pkg-config file fplll.pc

- fplll/bkz_param.cpp
- fplll/bkz_param.h
- fplll/pruner.cpp
- fplll/pruner.h
- tests/test_bkz.cpp
- tests/test_pruner.cpp
> Linear pruning probability

- configure.ac
- fplll/Makefile.am
Let's not merge this until @SnarkBoojum had a chance to tell us off or give us the thumbs up.
> clean up soname handling and bump library version

- fplll.pc.in
- fplll/pruner.cpp
Those two commits do what is described in the title.
Thanks,
> Two typos and a leaking pkgconfig file

- fplll/bkz.cpp
- tests/test_bkz.cpp
> fix segfault when blocksize > numrows

- fplll/enum/enumerate.cpp
- fplll/enum/enumerate.h
- 2 bugfixes for enumeration
- forced dynamic allocation of enumeration objects to avoid stack overflow.
> Enumwrapper

- .travis.yml
> echo back chosen compiler for greater clarity

- tests/test_bkz.cpp
fixes #170 and might possibly fixes #195
> run self-dual BKZ in at least dd precision

- .travis.yml
- fplll/io/json.hpp
Turns out we can support GCC 4.8 as discovered by @SnarkBoojum  at https://trac.sagemath.org/ticket/21221
> GCC 4.8 Support

- configure.ac
> permit --without-qd

- fplll/lll.h
fixes #212
reported and fix suggested by Erik Bray
> guard longdouble code appropriately

- .travis-check-style.sh
- .travis.yml
Modified the travis files to make the PRs #215 and #219 cross compatible.
> correcting the travis check style with macOS

- .travis-check-style.sh
> skip make check-style on travis' osx

- .travis.yml
- Makefile.am
- README.md
- fplll/Makefile.am
- tests/Makefile.am
This can guide what tests to write by highlighting which code paths are not tested.
> Automatic code coverage checks

- fplll/Makefile.am
- fplll/sieve/sieve_gauss.cpp
- fplll/sieve/sieve_gauss.h
- install headers
- move to fplll namespace
- be less verbose by default
> Fixes for sieving module

- fplll/bkz_param.cpp
- fplll/defs.h
- fplll/gso.h
- fplll/gso_gram.h
Fix bugs exposed when passing `-DDEBUG`
> `-DDEBUG` is completely unusable

- .travis.yml
- fplll/defs.h
- fplll/gso.cpp
- fplll/gso_gram.cpp
- fplll/gso_gram.h
- fplll/gso_interface.cpp
- fplll/gso_interface.h
- fplll/nr/dpe.h
- fplll/sieve/sieve_gauss.cpp
- fplll/sieve/sieve_gauss_str.h
- fplll/sieve/sieve_main.cpp
> Remove exit

- fplll/gso.cpp
- fplll/gso.h
- fplll/gso_gram.cpp
- fplll/gso_gram.h
- fplll/gso_interface.cpp
- fplll/gso_interface.h
- tests/test_lll_gram.cpp
No significant changes; I removed some unneeded comments (in `gso_gram.*`, `gso.*` and `gso_interface.*`), and also made the code somewhat clearer.
> Removed some unneeded comments with code snippets

- .travis.yml
- fplll/Makefile.am
- disable static library building
- only test the master branch
> Faster Travis-CI Checks

- fplll/bkz.cpp
- fplll/enum/enumerate.cpp
- fplll/gso.cpp
- fplll/gso_gram.cpp
> Issue 295 296

- fplll/nr/nr_FP_d.inl
- fplll/nr/nr_FP_ld.inl
> initialise FP<.> to zero

- fplll/gso_gram.h
See https://groups.google.com/d/msg/fplll-devel/QAlbTYGUbVU/YZoIgWfWAAAJ
> make MatGSOGram.row_swap public

- fplll/nr/nr_FP_dd.inl
Just to clear the `mpfr_t` `tf`.
> Clear a mpfr.

- README.md
This description is based only on my experience when installing it (twice) on my machine - I cannot guarantee that the same method works for installing fplll on other machines.
> Adding Windows 10 instructions to the readme

- README.md
- fplll/main.cpp
- fplll/nr/matrix.cpp
- fplll/nr/matrix.h
I propose to add a new output format in fplll for the matrices. This format is fully compatible with the Sage format, that is copy-paste in Sage will work without modification.
> New output format

- tests/test_bkz.cpp
> WITH_QD not HAVE_QD

- fplll/sieve/sampler_basic.cpp
- fplll/sieve/sieve_gauss.cpp
- fplll/sieve/sieve_main.cpp
Current sieve does not output the shortest vector found in the end. Just added that.
Also add some other instantiation declaration for other float types in case the users wanted to call them.
> minor fix sieve outputs and template inst.

- fplll/enum/enumerate_base.h
- fplll/wrapper.cpp
A new make check-style, with the correct clang-format command version?
> check-style bis

- README.md
See https://github.com/fplll/fplll/issues/371
> fix up reference

- Makefile.am
- fplll/nr/nr_FP.inl
- fplll/nr/nr_FP_d.inl
- fplll/nr/nr_FP_dd.inl
- fplll/nr/nr_FP_dpe.inl
- fplll/nr/nr_FP_ld.inl
- fplll/nr/nr_FP_misc.inl
- fplll/nr/nr_FP_mpfr.inl
- fplll/nr/nr_FP_qd.inl
- fplll/nr/nr_Z.inl
- fplll/nr/nr_Z_d.inl
- fplll/nr/nr_Z_l.inl
- fplll/nr/nr_Z_misc.inl
- fplll/nr/nr_Z_mpz.inl
- fplll/nr/nr_rand.inl
> also check .inl files

- README.md
- fplll/enum/enumerate_ext.cpp
- fplll/enum/enumerate_ext.h
Added some documentation to enumerate_ext.h and enumerate_ext.cpp (plus some non-breaking changes to the code for cleanliness). It's probably a good idea to add some const correctness too - will try and do this when I have more time.
> Extenum documentation

- .travis.yml
- fplll/gso_interface.h
See https://github.com/fplll/fpylll/commit/f723af4bbb05f0ca9a1ca52b643fe53218a92828
> Some basic sanity checking in MatGSO

- fplll.pc.in
- m4/ax_pthread.m4
- add pthread to pkg-config file
- updated autoconf-archive `m4/pthread.m4` to latest
> Pthread pc

- fplll/io/thread_pool.hpp
> update contrib thread_pool.hpp to latest

- fplll/io/thread_pool.hpp
- fplll/threadpool.cpp
performance isn't what it should be yet
also: https://trac.sagemath.org/ticket/28886
> disable by-default threadpool

- m4/ax_pthread.m4
Our local patches in ax_pthread.m4 made it to autoconf-archive,
going back to using autoconf-archive version.
> Updated m4/ax_pthread.m4 to latest autoconf-archive version

- configure.ac
- fplll.pc.in
- fplll/Makefile.am
- tests/Makefile.am
Here's my first shot at this. I'm sure it will look buggy as hell in the morning. Details in the individual commit messages.
> configure.ac: improved libqd detection

- configure.ac
- m4/ax_atomic.m4
> check for -latomic

- fplll/defs.h
- fplll/hlll.h
- fplll/lll.h
We've all had the "infinite loop in Babai" error code. But what does it mean?
This PR attempts to make this a bit nicer. In particular, we now have a wiki page (https://github.com/fplll/fplll/wiki/fplll-errors-FAQ) that is now printed to the user whenever an error message is printed. This is meant to be a solution to #244 .  
Please check the error codes/recommended solutions on the wiki page. I've only briefly encountered some of these errors before, and so it isn't likely to be 100% accurate.
> fplll faq page

- .github/workflows/docker.yml
- tools/Dockerfile
An FPLLL image on its own isn't that exciting but it can serve as a basis for FPyLLL and/or G6K images.
> Use Github Actions to publish Docker images

- fplll/enum/enumerate_ext.cpp
> fix enum ext callback issue

- fplll/enum/enumerate_ext_api.h
> minimal change to compile with gcc-11

- .gitignore
- configure.ac
- fplll/enum/evaluator.cpp
- fplll/gso.h
- fplll/io/thread_pool.hpp
- fplll/util.h
- m4/ax_cxx_compile_stdcxx.m4
- m4/ax_pthread.m4
- tests/test_svp.cpp
> Exacteval fix

- fplll/gso_interface.h
- fplll/wrapper.h
This PR is an attempt to fix #470.
The simplest way (I think) to do this is to add some documentation to the class. I believe what I've written is correct, but another pair of eyes would be appreciated.
> Fix #470 (document the role of u in LLL_reduction)

- fplll/enum-parallel/enumeration.h
- fplll/enum/enumerate_base.h
- fplll/hlll.cpp
- fplll/lll.h
- fplll/main.cpp
- fplll/nr/dpe.h
- fplll/nr/numvect.h
- fplll/pruner/pruner.cpp
- fplll/pruner/pruner.h
- fplll/pruner/pruner_optimize.cpp
- fplll/pruner/pruner_optimize_tc.cpp
- fplll/wrapper.cpp
> apply current make check-style
